apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: rbickerstaff@nowcom.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - dns01:
          azureDNS:
            clientID: 79313658-a2bb-4d52-80a8-9336dd85912b
            clientSecretSecretRef:
              name: azuredns-secret
              key: client-secret
            subscriptionID: c59ad15b-b901-4bf7-aa23-0e60665ec45e
            tenantID: 6dadecb4-3d69-41eb-98a0-cd3c988f5bd4
            resourceGroupName: trident.dev
            hostedZoneName: tridentcloud.dev
